server:
  port: 9090

spring:
  application:
    name: demo-service

  data:
    rest:
      base-path: 'demo-api'

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: demo3
    password: admin
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
